services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    image: novo-projeto-nextjs:1.0
    container_name: novo-projeto-app
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - novo-projeto-volume:/app/.next
      - ./src:/app/src
      - ./package*.json:/app/package*.json
      - /app/node_modules
    env_file:
      - .env.local
    environment:
      - PATH=/app/node_modules/.bin:/usr/local/bin:$PATH
    stdin_open: true
    tty: true
    command: npm run dev
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  novo-projeto-volume:
